### ISSUE TITLE
Onclickoutside does not work

### ISSUE THREAD

**Issue by moumny** [bharani91/react-select-popover#1]
Hi,

I installed react-select-popover and react-onclickoutside, but the popover doesn't hide when clicked outside.
What i'm I doing wrong ? 
I build my project using gulp and browserify

Best
Younes

**Comment by adesmet** [comment]
I have the same issue, otherwise it looks absolutely great

**Comment by moumny** [comment]
I works if copy paste the source in the poject. Must be some problem with imports

**Comment by bharani91** [comment]
@moumny, @adesmet Sorry for the delay guys. 
I've just pushed an update where I've updated to React 0.14.2. I think the issue was that react-onclickoutside needs ReactDOM (introduced in 0.14) to work.
