### ISSUE TITLE
lib has React.findDOMNode

### ISSUE THREAD

**Issue by kevinmic** [bharani91/react-select-popover#2]
I am taking a look at your project and I am getting warnings saying that you are using the deprecated feature React.findDOMNode.  

 Searching through your code in src/scripts/components/select-input.jsx you use ReactDOM.findDOMNode but in lib/select-input.js it is using React.findDOMNode.

By default when I install via npm it uses what is in lib.   Is there a reason what is in lib is different than what is in src?

**Comment by bharani91** [comment]
I had changed a few things in the gulp file in my earlier commit and I forgot to include the gulp task that converts the source files to into lib directory. I have fixed this issue now.
